[project]
name = "dinner-party"
revision = "1.0"

[providers]
env = "env://"
dotenv = "dotenv://"

[profiles.development]
POSTGRES_USER = { description = "Postgres Username", required = false, default = "postgres" }
POSTGRES_PASSWORD = { description = "Postgres Password", required = false, default = "db-password" }
POSTGRES_DB = { description = "Postgres Database", required = false, default = "postgres" }
DATABASE_URL = { description = "Database connection string", required = true, default = "postgresql://postgres:db-password@localhost:5432/postgres?schema=public" }

BETTER_AUTH_URL = { description = "BetterAuth URL", required = true, default = "http://localhost:3000" }
BETTER_AUTH_SECRET = { description = "BetterAuth secret", required = true, type = "base64", generate = { bytes = 64 }, providers = [
    "dotenv",
] }

GOOGLE_CLIENT_ID = { description = "Google OAuth client ID", required = true, providers = [
    "dotenv",
] }
GOOGLE_CLIENT_SECRET = { description = "Google OAuth client secret", required = true, providers = [
    "dotenv",
] }

[profiles.production]
POSTGRES_PASSWORD = { description = "Postgres Password", required = true }
DATABASE_URL = { description = "Database connection string", required = true }
BETTER_AUTH_URL = { description = "BetterAuth URL", required = true, default = "http://localhost:3000" }
BETTER_AUTH_SECRET = { description = "BetterAuth secret", required = true, type = "base64" }
GOOGLE_CLIENT_ID = { description = "Google OAuth client ID", required = true }
GOOGLE_CLIENT_SECRET = { description = "Google OAuth client secret", required = true }
