[project]
name = "dinner-party"
revision = "1.0"

[providers]
env = "env://"
dotenv = "dotenv://"

[profiles.default]
defaults.providers = ["env"]

[profiles.development]
POSTGRES_USER = { description = "Postgres Username", required = false, default = "dinner-party" }
POSTGRES_PASSWORD = { description = "Postgres Password", required = false, default = "dinner-party" }
POSTGRES_DB = { description = "Postgres Database", required = false, default = "dinner-party" }
DATABASE_URL = { description = "Database connection string", required = true, default = "postgresql://dinner-party:dinner-party@localhost:5432/dinner-party?schema=public" }

BETTER_AUTH_URL = { description = "BetterAuth URL", required = true, default = "http://localhost:3000" }
BETTER_AUTH_SECRET = { description = "BetterAuth secret", required = true, type = "base64", generate = { bytes = 64 }, providers = [
    "dotenv",
] }

GOOGLE_CLIENT_ID = { description = "Google OAuth client ID", required = true, providers = [
    "dotenv",
] }
GOOGLE_CLIENT_SECRET = { description = "Google OAuth client secret", required = true, providers = [
    "dotenv",
] }
