//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type DinnerParty = $ModelResult<$Schema, "DinnerParty">;
export type Comment = $ModelResult<$Schema, "Comment">;
export type DinnerPartyGuest = $ModelResult<$Schema, "DinnerPartyGuest">;
export type AccessCode = $ModelResult<$Schema, "AccessCode">;
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export const Role = $schema.enums.Role.values;
export type Role = (typeof Role)[keyof typeof Role];
