name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
      with:
        version: 10
    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: "pnpm"
    - name: Install secretspec
      run: curl -sSL https://install.secretspec.dev | sh
    - run: pnpm install --frozen-lockfile
    - run: secretspec run --profile production --provider env -- pnpm run build
      env:
        BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    - run: pnpm run lint
    - run: pnpm run generate
    - run: pnpm run migrate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
